BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
        Button:
            text: 'Square'
            on_press: app.handle_calculate(int(input_number.text))
        Label:
            id: output_label
            color: (0.5, 0, 0.5, 1)
   Label:
        text: 'Enter a number and press Square'
